In [2]:
import torch

In [3]:
a = torch.tensor([[1,2,3],[3,4,5]]) # 2x3
b = torch.tensor([[1,2,3],[3,4,5]]).T # 3x2

In [4]:
a.shape, b.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [5]:
a[1:,] # second row and all columns

tensor([[3, 4, 5]])

In [6]:
b[:,1] # all rows and second column

tensor([3, 4, 5])

In [9]:
a.shape, a.unsqueeze(-1).shape

(torch.Size([2, 3]), torch.Size([2, 3, 1]))

In [10]:
import numpy as np
A = np.array([0, 1, 2])

B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
              


In [12]:
A.shape, B.shape

((3,), (3, 4))

In [19]:
torch.tensor(A[:, np.newaxis]) == torch.tensor(A).unsqueeze(-1)

tensor([[True],
        [True],
        [True]])

In [22]:
np.einsum("i, ij -> ij", A, B) 
# this multiplies the elements in A with corresponding rows in B


array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [24]:
np.einsum("i, ij -> j", A, B) 
# this multiplies the elements in A with corresponding rows in B and then sums them column wise

array([20, 23, 26, 29])

In [26]:
np.einsum("i, ij -> i", A, B) 
# this multiplies the elements in A with corresponding rows in B and then sums them row wise. then transposes

array([ 0, 22, 76])